---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/maidenwa/public_html/
    - /bin/rsync index.html $DEPLOYPATH
    - /bin/rsync -R vendor $DEPLOYPATH
    - /bin/rsync -R assets $DEPLOYPATH
    - /bin/rsync -R plugins $DEPLOYPATH
    - /bin/rsync -R js $DEPLOYPATH
    - /bin/rsync -R PruebaNoUsuarios $DEPLOYPATH
    - /bin/rsync -R Identidad-Virtual $DEPLOYPATH
    - /bin/rsync -R NFCare $DEPLOYPATH
    - /bin/rsync about-us.html $DEPLOYPATH
    - /bin/rsync blog-details.html $DEPLOYPATH
    - /bin/rsync products.html $DEPLOYPATH
    - /bin/rsync product-details.html $DEPLOYPATH
    - /bin/rsync checkout.html $DEPLOYPATH
    - /bin/rsync contact.html $DEPLOYPATH
    - /bin/rsync licese.txt $DEPLOYPATH
    - /bin/rsync special-offer.html $DEPLOYPATH
    - /bin/rsync terms.html $DEPLOYPATH
    - /bin/rsync testimonials.html $DEPLOYPATH
    - /bin/rsync product-details.php $DEPLOYPATH
    - /bin/rsync product-detail-prueba.php $DEPLOYPATH